data:
  batch_size: 512
  dataset_dir: './data/ETT'
  dataset_name: 'ETTh2'
  dataset_filename: './data/ETT/ETTh2.csv'
  task_type: 'M2M'
  freq: 'S'  # if freq=B in_channels_covar=7 if freq=S in_channels_covar=25
  target: 'OT'
  split_ratio: [0.6, 0.2, 0.2]
  num_workers: 0

model:
  in_lens: 720  # latter-hist_len=336
  label_lens: 48
  out_lens: 96 # [96, 192, 336, 720]M2M  [24, 48, 96, 192, 336, 720]S2S
  num_nodes: 7
  num_hidden: 512
  out_channels_dec: 32
  num_hidden_temp_dec: 16
  in_channels_covar: 25
  num_layers_enc: 2
  num_layers_dec: 2
  drop_rate: 0.2
  if_ln: True
  if_revin: True
  embed_type: 'timeF' # choosen from [timeF, fixed, learned]


train:
  lr: 0.00022400011085303776
  epochs: 100
  patience: 40
  is_training: True
  model_id: 'ETTh1_720_96'
  model: 'TiDE'
  checkpoints: './checkpoints/TiDE/'
  use_amp: False # use automatic mixed precision training
  use_multi_gpu: False
  adjust_lr: 'type1'
  do_predict: False
  itr: 1 # experiments time
  test_flop: False

test:
  predict_lens: [1, 3, 6, 12]
  test_flop: False
  save_epoch: 43