data:
  batch_size: 32
  dataset_dir: './data/ELEC'
  dataset_name: 'ELEC'
  dataset_filename: './data/ELEC/ELEC.csv'
  task_type: 'M2M'
  freq: 'B'  # if freq=B in_channels_covar=7 if freq=S in_channels_covar=25
  target: 'OT'
  split_ratio: [0.7, 0.1, 0.2]
  num_workers: 0

model:
  in_lens: 720
  label_lens: 48
  out_lens: 96 # [96, 192, 336, 720]M2M  [24, 48, 96, 192, 336, 720]S2S
  num_nodes: 321
  num_hidden: 1024
  num_hidden_covar: 64
  num_hidden_temp_dec: 64 # final_decoder_hidden temporal decoder
  in_channels_covar: 7
  out_channels_covar: 4
  out_channels_dec: 8 # decoders' output
  num_layers_enc: 2
  num_layers_dec: 2
  if_ln: True
  drop_rate: 0.5
  if_revin: False
  embed_type: 'timeF' # choosen from [timeF, fixed, learned]


train:
  lr: 9.99e-4
  epochs: 10
  patience: 3
  is_training: True
  model_id: 'ELEC_720_96'
  model: 'TiDE'
  checkpoints: './checkpoints/TiDE/'
  do_predict: False
  itr: 5 # experiments time
  test_flop: False

test:
  predict_lens: [1, 3, 6, 12]
  test_flop: False
  save_epoch: 43